// These are action types that will be used within the app
const constants = {
	ADD_EXPENSE_GROUP : "ADD_EXPENSE_GROUP",
	EDIT_EXPENSE_GROUP : "EDIT_EXPENSE_GROUP",
	SAVE_EXPENSE_GROUP : "SAVE_EXPENSE_GROUP",
	REMOVE_EXPENSE_GROUP : "REMOVE_EXPENSE_GROUP",
	/* Children of expense groups */
	ADD_EXPENSE_GROUP_CHILD : "ADD_EXPENSE_GROUP_CHILD",
	EDIT_EXPENSE_GROUP_CHILD : "EDIT_EXPENSE_GROUP_CHILD",
	SAVE_EXPENSE_GROUP_CHILD : "SAVE_EXPENSE_GROUP_CHILD",
	REMOVE_EXPENSE_GROUP_CHILD : "REMOVE_EXPENSE_GROUP_CHILD",
};

module.exports = constants;